name: CI pipeline

on: 
  push:
    branches: [main]

jobs: 
  Test-and-build:
    runs-on: windows-latest
    steps:
      - name: Repository'ni yuklash
        uses: actions/checkout@v4

      - name: Node.js o'rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: npm install
        run: npm install

      - name: Test buyrug'ini ishga tushurish
        run: npm run test

      - name: Build qilish
        run: npm run build
